### ISSUE TITLE
Line 280 in sugarcrm.py seems to block using custom modules

### ISSUE THREAD

**Issue by jhoffmann** [ryanss/sugarcrm#1]
I'm trying to use get_entry_list() on a custom module, so I've got something like:

```
import sugarcrm

class CustomModule(sugarcrm.SugarObject):
    module = "custom_Module"

q = CustomModule(name="Something")
r = session.get_entry_list(q)
```

But it bombs on line 280 because my CustomModule class doesn't exist.  If I simply comment this line out, it works fine.

Fairly new to Python, is there any way around this?

**Comment by ryanss** [comment]
I believe I've fixed the issue. The results returned from `get_entry_list` will now have a class type matching the class passed to the method (in your example `CustomModule`) and will not cause an exception if it can't find that class type in the list of SugarCrm object types defined in `sugarcrm.py`.

**Comment by jhoffmann** [comment]
Thanks Ryan, I'll give a try shortly!
